version: "3.7"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
  node:
    build: ./node
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - mongo
      - nginx
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: FinTech
      MONGO_INITDB_ROOT_PASSWORD: FinTechDemo
  mongo-express:
    image: "mongo-express:latest"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: FinTech
      ME_CONFIG_MONGODB_ADMINPASSWORD: FinTechDemo