version: "3"
services:
  node:
    build: ./node
    restart: always
    ports:
      - "5555:5555"
    privileged: true
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: FinTech
      MONGO_INITDB_ROOT_PASSWORD: FinTechDemo
  mongo-express:
    image: "mongo-express:latest"
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: FinTech
      ME_CONFIG_MONGODB_ADMINPASSWORD: FinTechDemo
